/*
 * Perch API
 * Interactive documentation functionality is incomplete and may not work as expected. We recommend you connect with a REST client such as Postman, Httpie, or even plan old CURL.   Obtain your API username, password, and key from your <a href=\"https://app.perchsecurity.com/user/groups\" target=\"blank\">group settings</a>   <br><h4>Root URL</h4><table class=\"parameters table table-bordered table-striped\"><tr><td>Base URL</td><td>https://api.perch.rocks</td></tr><tr><td>Version</td><td>v1</td></tr></table>   <br><h4>Headers</h4><table class=\"parameters table table-bordered table-striped\"><tr><td>x-api-key</td><td>(your api key from the group settings page)</td></tr><tr><td>Authorization</td><td>Bearer (your access token returned from /auth/access_token)</td></tr></table>
 *
 * OpenAPI spec version: v1
 * Contact: help@perchsecurity.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.15
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.PerchApi);
  }
}(this, function(expect, PerchApi) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('SuppressionsAndEscalations', function() {
      beforeEach(function() {
        instance = new PerchApi.SuppressionsAndEscalations();
      });

      it('should create an instance of SuppressionsAndEscalations', function() {
        // TODO: update the code to test SuppressionsAndEscalations
        expect(instance).to.be.a(PerchApi.SuppressionsAndEscalations);
      });

      it('should have the property label (base name: "label")', function() {
        // TODO: update the code to test the property label
        expect(instance).to.have.property('label');
        // expect(instance.label).to.be(expectedValueLiteral);
      });

      it('should have the property truePositives (base name: "true_positives")', function() {
        // TODO: update the code to test the property truePositives
        expect(instance).to.have.property('truePositives');
        // expect(instance.truePositives).to.be(expectedValueLiteral);
      });

      it('should have the property falsePositives (base name: "false_positives")', function() {
        // TODO: update the code to test the property falsePositives
        expect(instance).to.have.property('falsePositives');
        // expect(instance.falsePositives).to.be(expectedValueLiteral);
      });

      it('should have the property escalations (base name: "escalations")', function() {
        // TODO: update the code to test the property escalations
        expect(instance).to.have.property('escalations');
        // expect(instance.escalations).to.be(expectedValueLiteral);
      });

    });
  });

}));
